# Este arquivo configura o analisador estático do Dart.
# Mais informações: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  # Ignora arquivos gerados automaticamente por pacotes como build_runner, json_serializable ou freezed.
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  # Você pode alterar a severidade de certos problemas aqui.
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore # Ignora os avisos de // TODO: no código

linter:
  # Lista de todas as regras disponíveis: https://dart.dev/lints
  rules:
    # ------------------------------------------------------------------------
    # Formatação e Estilo
    # ------------------------------------------------------------------------
    prefer_single_quotes: true             # Usa aspas simples em vez de duplas
    require_trailing_commas: true          # Exige vírgula no final de parâmetros/listas para melhor formatação pelo Dartfmt
    sort_child_properties_last: true       # Força a propriedade `child` ou `children` a ser a última nos widgets
    prefer_const_constructors: true        # Exige o uso de `const` em construtores sempre que possível
    prefer_const_declarations: true        # Prefere `const` para variáveis que nunca mudam
    prefer_const_literals_to_create_immutables: true # Usa `const` em listas e mapas imutáveis

    # ------------------------------------------------------------------------
    # Boas Práticas e Segurança de Código
    # ------------------------------------------------------------------------
    always_declare_return_types: true      # Exige que métodos e funções declarem seu tipo de retorno
    avoid_dynamic_calls: true              # Evita chamar métodos em objetos do tipo `dynamic`
    avoid_print: true                      # Evita o uso de `print` em produção (use `debugPrint` ou um logger)
    avoid_empty_else: true                 # Evita blocos `else` vazios
    cancel_subscriptions: true             # Alerta se você esquecer de cancelar StreamSubscriptions
    close_sinks: true                      # Alerta se você esquecer de fechar Sinks/Controllers
    unnecessary_await_in_return: true      # Evita `await` desnecessário quando você já está retornando uma Future