name: app_anemia
description: Diagnóstico de Anemia Offline com Edge-AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3     # Para gerar os hashes SHA-256 irreversíveis
  encrypt: ^5.0.3    # Para a criptografia RSA de chave pública
  flutter:
    sdk: flutter
  
  # =========================================================================
  # 1. INTERFACE E COMPONENTES VISUAIS
  # =========================================================================
  cupertino_icons: ^1.0.6

  # =========================================================================
  # 2. IA E PROCESSAMENTO DE IMAGEM (EDGE-AI)
  # =========================================================================
  camera: ^0.11.0             # Acesso direto à câmera do hardware
  onnxruntime: 1.4.1         # ATUALIZADO: Motor C++ atualizado para múltiplas sessões
  image: ^4.2.0               # Redimensionamento dos pixels para 224x224
  google_mlkit_face_detection: ^0.9.0
  # =========================================================================
  # 3. BANCO DE DADOS LOCAL (OFFLINE-FIRST)
  # =========================================================================
  shared_preferences: ^2.2.2  # Armazena o histórico de exames no aparelho

  # =========================================================================
  # 4. TELEMETRIA E SINCRONIZAÇÃO NUVEM (API)
  # =========================================================================
  http: ^1.6.0                # Realiza requisições POST para o FastAPI
  battery_plus: ^7.1.1        # Coleta a porcentagem da bateria
  geolocator: ^14.0.3         # Coleta as coordenadas (Latitude/Longitude)
  
  # =========================================================================
  # 5. GERENCIAMENTO DE PERMISSÕES NATIVAS
  # =========================================================================
  permission_handler: ^11.3.1 # Solicita permissão de Câmera e GPS ao usuário
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # =========================================================================
  # 6. ARQUIVOS EMBUTIDOS NO APLICATIVO (ASSETS)
  # =========================================================================
  # Aqui declaramos os modelos de IA para que o Flutter os embuta no app
  assets:
    - assets/vit_hemoglobina_mobile_final.onnx  # Nosso cérebro visual principal
    - assets/xgboost_tabular_final.onnx         # NOVO: Modelo de fusão com Idade/Sexo